APP_MODE: debug
HTTP_PORT: 8000
UPLOAD_MODEL: HuaweiCloud

MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_USER_NAME: root
MYSQL_PASSWORD: Jinziguan123
MYSQL_DB_NAME: imall

REDIS_DB: redis
REDIS_ADDR: 127.0.0.1:6379
REDIS_PASSWORD: 
REDIS_DB_NAME: 2

ACCESS_KEY:
SECRET_KEY:
BUCKET:
HUAWEI_SERVER:

VALID_EMAIL:
SMTP_HOST:
SMTP_EMAIL:
SMTP_PASS:

PHOTO_HOST: /static/photo
PRODUCT_PHOTO_HOST: /static/photo/product
AVATAR_PATH: /static/photo/avatar