// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/addresses": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "展示用户最新地址",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "手机号",
                        "name": "phone",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "地址",
                        "name": "address",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "创建地址",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "手机号",
                        "name": "phone",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "地址",
                        "name": "address",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/addresses/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "展示用户所有收货地址",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "手机号",
                        "name": "phone",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "地址",
                        "name": "address",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/carousels": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "显示轮播图",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "验证Token",
                "parameters": [
                    {
                        "description": "Token",
                        "name": "Token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "summary": "用户更新信息",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "昵称",
                        "name": "nick_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "用户登陆",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "10004": {
                        "description": "密码不正确",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "10010": {
                        "description": "用户不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "30003": {
                        "description": "Token初始化失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "昵称",
                        "name": "nick_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密钥",
                        "name": "key",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "10002": {
                        "description": "用户已存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "10006": {
                        "description": "密码加密失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "密钥错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/sending-email": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "发送邮件",
                "parameters": [
                    {
                        "description": "操作类型",
                        "name": "operationType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "对方邮箱",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "10010": {
                        "description": "用户不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "30003": {
                        "description": "鉴权失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "30007": {
                        "description": "发送邮件失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/valid-email": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "解绑邮箱",
                "parameters": [
                    {
                        "description": "Token",
                        "name": "Token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "30001": {
                        "description": "管理员错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "30002": {
                        "description": "Token过期",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "非法Token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v2/admin/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "管理员登陆",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "user_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "10004": {
                        "description": "密码错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "10010": {
                        "description": "用户不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "30003": {
                        "description": "鉴权失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v2/admin/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "管理员注册",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "user_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "10002": {
                        "description": "用户已存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "10006": {
                        "description": "密码加密失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v2/carousels": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "创建轮播图",
                "parameters": [
                    {
                        "description": "轮播图保存路径",
                        "name": "imgPath",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "40001": {
                        "description": "数据库错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "goMall电商系统",
	Description:      "后台API接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
